name = "ChartmetricScraper"
uuid = "77c1d96d-5cb6-4418-b859-b32a1c7d1d5f"
authors = ["Daniel Winkler <danielw2904@disroot.org>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"

[compat]
HTTP = "0.8"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
